### ISSUE TITLE
[2.2.5] Cannot install lxde-gtk3 : conflict between lxdm and lxdm-gtk3 on install.

### ISSUE THREAD

**Issue by FredBezies** [deadhead420/arch-linux-anywhere#124]
I tried to install lxde-gtk3 and it doesn't work.

There is a conflict between lxdm-gtk3 and lxdm. See attached  screenshot. 

![lxdm-conflict](https://cloud.githubusercontent.com/assets/8571419/21945898/349963e2-d9de-11e6-9e8d-da5b2ea1b31d.png)

Sorry it is in french, but easily understandable.

**Comment by deadhead420** [comment]
Thanks for this. I never notice stuff like this due to not having much time to test every configuration of de + dm, etc... This only seems to happen when selecting lxde-gtk3 + lxdm, works fine with any other dm. Anyway I fixed the bug by adding lxdm-gtk3 instead of lxdm if the user selects gtk3. Thanks again for the report.
