### ISSUE TITLE
Netctl installs with NetworkManager causing conflicts

### ISSUE THREAD

**Issue by truency** [deadhead420/arch-linux-anywhere#126]
I've been trying to reproduce this via VirtualBox after I installed the 3rd time on my main SSD. Basically what kept happening was when I installed ArchAnywhere, Netctl would install with NetworkManager causing a bunch of issues. I ended up removing NetworkManager and just using wifi-menu to connect to WiFi. 

Problem: NetworkManger Installs with Netctl, Netctl installs with NetworkManager (causes conflict)

**Comment by deadhead420** [comment]
This makes sense because netctl is a part of the base package group so it is always installed. However the installer should only enable the service for the network util you selected. The only way they can cause conflicts with eachother is if both services are enabled which couldn't be happening in the installer. The case statement which enables a network service can only enable one service (based on your selection). I've tested with selecting netctl, networkmanager is not installed and netctl service is enabled at boot. Installed selecting networkmanager both netctl and networkmanager are installed (since netctl is in base) but only NetworkManager.service was enabled at boot.... Not sure how you could have ended up with both services enabled since it is only possible for the script to enable one service out of the two. What kind of issues were you running into?

**Comment by truency** [comment]
Every time I boot I have to run this bash script in order to connect:
```
#!/bin/bash
sudo ip link set dev wlp2s0 down
sudo wifi-menu
```

It's simplistic, and it works 50% of the time. I have to reboot constantly in order for it to connect. If it doesn't connect, wifi-menu will return: 'No networks found'. On the 2nd or 3rd reboot it finally brings up the list.

I also have to blacklist ``acer-wmi`` via modprobe.

**Comment by deadhead420** [comment]
Closing this issue for now as it seems to be a problem with your chipset and not the installer. What wifi chipset are you using?

**Comment by truency** [comment]
02:00.0 Network controller: Intel Corporation Wireless 3165 (rev 81)

Yes and no. When I run Ubuntu, or Antergos, or any other linux-based distribution, all I do is disable acer-wmi (modprobe) and it works flawlessly. This is the second time using Arch-Anywhere. Both times selecting netctl. First install worked flawlessly, this time around it doesn't work as explained above as per the reason why I don't know.

**Comment by d3rrial** [comment]
I had the same problem. It was fixed once I disabled dhcpcd
