### ISSUE TITLE
Missing packet suggestion

### ISSUE THREAD

**Issue by MakuSensei** [deadhead420/arch-linux-anywhere#132]
Hi, I have found that to compile there is a problem for not having the following basic packages
Base-devel, make, cmake, binutils
I also want to recommend if you can include in the arch-anywhere repository the pamac and octopi

**Comment by deadhead420** [comment]
Base devel is included in installer and it includes all packages needed to compile from source. You must select it during install or install it afterwards. Closing this issue since it isn't really an issue. I will add more packages to the arch-anywhere repo when I have time to work on the script used for updating the repo. Is too much work to add an update packages manually. Will probably see these packages in a future release.
