### ISSUE TITLE
Error: you must select a root partition before continuing with install

### ISSUE THREAD

**Issue by verdie-g** [deadhead420/arch-linux-anywhere#199]
Hi,
After choosing the languages, wifi, ... I have to choose the method of partitioning. But when I select "Manual Partition Drive" I get the error
`Error: you must select a root partition before continuing with install`
After pressing Ok, a message is displayed:
`/usr/bin/archlinux-aywhere: line 655: /tmp/part.list: No such file or directory`
`rm cannot remove '/tmp/part.list: No such file or directory` 
And the message box about the root partition appears again.

Any idea where it comes from ?

**Comment by deadhead420** [comment]
What install language are you using?

**Comment by verdie-g** [comment]
I'm using english

**Comment by condor2** [comment]
What version you use?
Check the md5sum to see if is exact the same.

**Comment by verdie-g** [comment]
2.2.6 and the checksums match

**Comment by deadhead420** [comment]
Are you installing in vbox? Real hardware? Am entirely unable to recreate this issue.

**Comment by verdie-g** [comment]
I'm installing it on a new computer I just bought (Dell XPS 13). I guess there is no point in downloading the iso again if the cheksums match :/

Moreover, do you know why there is this infinite loop ? When I press 'Ok' the message about not finding par.list is display one quarter of second and the message box appears again so I'm force to shutdown the computer.

**Comment by deadhead420** [comment]
Really not sure because I'm unable to recreate this in vbox or real hardware. There is however one thing I can suggest. I've added a new feature which will be released in 2.2.7 which can be used to update to latest scripts from github. This feature isn't in 2.2.6 however you can download the latest config file to enable it. This way you can try downloading the latest scripts and it may fix the issue (many updates have been made to manual partitioning). To do this you will need to use wget before the install to fetch arch-anywhere.conf. The command to do that is:

# wget -O /etc/arch-anywhere.conf https://raw.githubusercontent.com/deadhead420/arch-linux-anywhere/master/etc/arch-anywhere.conf

After running that command you will be able to use the new update option to update all scripts, to do that simply run:

# arch-anywhere -u

You will see output saying the scripts have been updated then try running the installer again. Lots of updates have been made to partitioning and it should work without any issues. Nonetheless its very confusing you're having this issue with the current ISO because neither I nor any of the testers have been able to recreate it. Try updating the scripts with the above method and attempt the install again, let me know if it works.

**Comment by deadhead420** [comment]
Also if possible can you show the output of the command:

`lsblk`

**Comment by verdie-g** [comment]
I can now access the partition menu but no drive are listed.

lsblk outputs the following:
```
loop0    7:0 0 339.5M 1 loop /run/archiso/sfs/airootfs
sda      8:0 1 3.8G   0 disk
-- sda1  8:1 1 3.8G   0 part /run/archiso/bootmnt
```

**Comment by verdie-g** [comment]
My main boot is windows. I didn't create a partition but I let a empty space for arch. Should I create an ext4 partition from windows ?

**Comment by deadhead420** [comment]
Shouldn't be necessary.... Looks like your drive is only 3.8G? That might be the problem. Why is it so small? Windows couldn't even fit on there.

**Comment by verdie-g** [comment]
3.8G is my USB key. I guess my drive isn't detected

**Comment by deadhead420** [comment]
So it seems... If its not listed in the lsblk command its not detected at all in linux. What I would recommend is to do a search for your exact laptop brand + model number in the format: (brand model number linux drive not detected) you may find more info that way. I'm also assuming the drive in question is an SSD, you may find more info here: (https://wiki.archlinux.org/index.php/Solid_State_Drives#Troubleshooting). Also may want to try booting a live cd of another distro (not arch based) and see if it shows up when running lsblk, if so it would be best to file a bug report on archlinux.org.

**Comment by verdie-g** [comment]
I tried https://wiki.archlinux.org/index.php/Dell_XPS_13_(9350)#Cannot_find_root_device but it doesn't help. Anyway I guess it's a problem with my hardware, I'll try to figure out how to solve it.
Thanks for your time :)

**Comment by deadhead420** [comment]
No problem. Closing issue since it isn't related to the installer. Good luck.
