### ISSUE TITLE
intel ucode doesn't get installed anymore

### ISSUE THREAD

**Issue by allannk** [deadhead420/arch-linux-anywhere#215]
In the new release, I have to manually install `intel-ucode` in chroot before rebooting. It is properly configured in `/boot/loader/entries/arch.conf` (systemd-boot, haven't tested the others), and causes the system not to boot until installed.

**Comment by allannk** [comment]
Watching the install process, I realized today that for a short moment, an error is printed on top of the progress bar while installing the base system, stating that there is some permission issue regarding a folder and a mention of intel-ucode.

**Comment by deadhead420** [comment]
Hey man. I've removed intel-ucode from the script simply because its been an on-going pain in the ass. I don't really have a way to test it and its given nothing but problems so it has been removed and will be up to the user to install (its really not necessary anyway).

**Comment by allannk** [comment]
Ah okay, fair point :-)
Should be removed from the boot entry too then, in
/boot/loader/entries/arch.conf (which is probably generated from the
template in systemd-boot. Thanks for the response

**Comment by deadhead420** [comment]
No problem. On second thought I think I'm going to prompt the user if they would like to install ucode after the install... I really don't know why it fails but I'm going to change it so instead of installing at the same time as everything else it will install seperately after the install. I'll add this feature but I won't be able to test it. I will be releasing a new ISO in a few hours 2.2.7. If you wouldn't mind testing it after I release and let me know if it still fails and if it does I will remove it. I'll let you know when I release new version.

**Comment by deadhead420** [comment]
I've done a new release. Not sure if this bug is still present but it should be fixed

**Comment by cjmccormick** [comment]
When I tried to update the intel ucode it just hangs on 100% for me, tried with two different installs

**Comment by allannk** [comment]
The problem have gotten worse now - the installation of intel-ucode fails
without any detailed message, and the image is no longer added in the boot
chain. I can provide the install log if needed, but it contains no
information from what I can tell

**Comment by deadhead420** [comment]
I've gotten rid of ucode entirely because its a buggy piece of crap and doesn't want to work at all. I've left all the code in the scripts but have commented it all out. If anyone wants to figure it out they can feel free but for now the installer does not support intel ucode and the user may choose to install it after install if they wish. Closing this issue for now, ucode is no more.
