### ISSUE TITLE
Add option to use syslinux

### ISSUE THREAD

**Issue by spsf64** [deadhead420/arch-linux-anywhere#28]
Can you add an option to use syslinux instead o grub?
With syslinux you can also be able to install the loader to partition (/), very useful for dual booters where you can keep the current windows loader and chainload syslinux.
TIA

**Comment by deadhead420** [comment]
It took me nearly the whole weekend to get this working with UEFI support. Proud to announce I have finally figured it all out. The next version of Arch Anywhere (2.2.2) will include an option for both grub and syslinux. I use the same syslinux config used in the arch anywhere ISO.

EFI ended up being a major headache. When booting EFI with syslinux it requires the kernel and initramfs to be saved on the ESP. This means if someone mounts their ESP at /boot/efi and the kernel and initramfs is installed at /boot the system will not be able to boot because the esp=/boot/efi cant access /boot to load the kernel.

If useing EFI boot with syslinux it is highly recommended to mount your esp at /boot so that syslinux will be able to load the kernel.

I wrote some code to detect if the user has the esp mounted at /boot/efi OR /boot/EFI and if so it makes a copy of the kernel and initramfs on $esp so that syslinux is able to load the kernel and displays a warning message to the user that they will need to copy over new kernels after update.

Closing this issue. Expect to see this feature along with many fixes and improvements in the next release very soon (2.2.2).

**Comment by spsf64** [comment]
Thank you! 
Waiting for next release to test and give feedback!

**Comment by spsf64** [comment]
@deadhead420 Hi and thank you for including syslinux, however I tried the latest iso and noticed there is no option so install it to / (root partition) instead of mbr. 
Could you add this option too?
The command for syslinux would be: "syslinux-install_update -i" (instead of -iam).
