### ISSUE TITLE
Brazil timezone and subzone select bug

### ISSUE THREAD

**Issue by OscarHolst** [deadhead420/arch-linux-anywhere#31]
When user is promted to set timezone and choose "Brazil", and on the subzone selection screen if you choose Brazil again, you just get sent back to the first timezone screen.

**Comment by deadhead420** [comment]
I know what you're talking about.. Its like that for most of the timezones. America is the same way. If you select america again it goes back to the first list. The reason for this is because to create the list of timezones I use the "find" command to list all the directories under /usr/share/zoneinfo/. Some of the directories like for example america and brazil contain symlinks back to themselves for whatever reason... So pretty much what is happening is my find command sees that symlink and displays it in the list of timezones. When you select this it simply symlinks you back to the top /usr/share/zoneinfo directory (from /usr/share/zoneinfo/Brazil) symlink: /usr/share/zoneinfo/Brazil > /usr/share/zoneinfo/Brazil/Brazil. Not a very big bug because it is doing what it should simply symlinking back, however I see how it could come off as a bug. I'll look into a way around it... I think I already know what i can do... When "Brazil" is first selected it sets a variable ZONE=Brazil then jumps into the result of the find command on the brazil dir. I could simply pipe sed to exclude $ZONE then the symlink wont be listed in the find command... Will fix it up in a bit. Haven't had much time to work on arch anywhere lately but want to try and get an update out by the weekend

**Comment by OscarHolst** [comment]
I see..My bad... My first thought was "OMG A BUG!", but it's just doing what it should, as you said.
However, awesome if it's possible to fix!

**Comment by deadhead420** [comment]
Got it all taken care of.... Was as simple as adding ' | grep -v "$ZONE" ' to the command. The symlinks no longer show in the timezone menus. Fix will be in the next release 2.2.0. I'm finishing testing now and will release in just a few hours. All issues have been resolved
