### ISSUE TITLE
Support NVMe SSD out of the box

### ISSUE THREAD

**Issue by sdeleuze** [deadhead420/arch-linux-anywhere#326]
As mentioned on the [Dell XPS 13 Archlinux wiki](https://wiki.archlinux.org/index.php/Dell_XPS_13_(9350)#Cannot_find_root_device) (and various other tutos like [this one](http://www.cio.com/article/3098030/linux/how-to-install-arch-linux-on-dell-xps-13-2016-in-7-steps.html)), it is necessary to add `nvme` module to `/etc/mkinitcpio.conf` to make it possible to boot on [NVMe](https://en.wikipedia.org/wiki/NVM_Express) SSD.

This kind of hard drive is more and more used (for example for on popular Dell XPS 13 and XPS 15), so while chrooting the install, and the missing module to `/etc/mkinitcpio.conf` and running `mkinitcpio -p linux` is not super hard, but I think it deserves to be supported out of the box.

I tend to think just adding `nvme` module by default to `/etc/mkinitcpio.conf` would be enough (it won't hurt for regular SATA systems). Doing that allow my Dell XPS 13 to boot as expected.

**Comment by pnedkov** [comment]
@sdeleuze, correct me if I am wrong but as I understand it from the link you provided, the problem only occurs when you upgrade from linux kernel 4.3 to 4.4 or newer. Which means that this will not affect the fresh install since the current linux kernel version in the Arch repo is 4.10. On the other hand [here](https://wiki.archlinux.org/index.php/Solid_State_Drives/NVMe) it says:

_It **may** be needed to add the nvme module to the MODULES array within /etc/mkinitcpio.conf to successfully boot into the root filesystem._

Can you config that "nvme" module must or may not be included in `/etc/mkinitcpio.conf`? I do not have the required hardware in order to test and reproduce it.

**Comment by sdeleuze** [comment]
Nope, I can confirm from my own experience and a huge number of people complaining on forums that this issue impact all 4.3+ kernel including 4.10. So in practice when you do a fresh install on an XPS 13, XPS 15 or any very recent NVME based SSD laptop Arch Linux simply don't boot after the install.

You can have a look to the last step of [this famous tuto](http://www.cio.com/article/3098030/linux/how-to-install-arch-linux-on-dell-xps-13-2016-in-7-steps.html) to have the confirmation.

**Comment by pnedkov** [comment]
Got it. Let me ask you a simple question: If we add the `nvme` module in `/etc/mkinitcpio.conf` (MODULES="nvme") right before we run `mkinitcpio -p linux` when the boot device is an nvme device, will this solve the problem? If it is that simple I could fix it during the weekend but I need someone to test it on a real hardware before it gets merged.

**Comment by sdeleuze** [comment]
Yes it will, this is what I do to make it work on my Dell XPS 13 and Dell Precision 5520.

**Comment by pnedkov** [comment]
#339 

Please give it a try. I just tested it on a VM with UEFI, grub and no encryption and it works.
I know we are running mkdinitcpio command twice but I really **really** did not want to touch the existing code.

**Comment by sdeleuze** [comment]
Works with and without encrypted partions 👍
