### ISSUE TITLE
Installing on 4GB USB

### ISSUE THREAD

**Issue by tjespe** [deadhead420/arch-linux-anywhere#332]
I want to install Arch on a 4GB USB. However, I only have 3.6GB left for the root partition when subtracting the EFI boot partition, and the lower limit for the root partition in the `arch-anywhere` script is 4GB.

Why is it so high? Can I edit the files before running the script so that it will install?

**Comment by pnedkov** [comment]
I do not know why 4GB has been chosen for a minimum partition size but I can give you an idea how to work-around it. Look in configure_device.sh and more specifically this line:
`[4-9]G|[1-9][0-9]*G|[4-9].*G|[4-9],*G|T)`

You can change it according to your needs. For example:
`[3-9]G|[1-9][0-9]*G|[3-9].*G|[4-9],*G|T)`

It will be a good idea to update the installer before that:
`arch-anywhere -u`

Good luck.

**Comment by pnedkov** [comment]
@tjespe any luck?

**Comment by tjespe** [comment]
Yes it worked fine without any issues. Thank you very much.

**Comment by pnedkov** [comment]
Cool, I am glad it worked for you.
base-devel + full xfce + browser + some additional software has around 2.5G footprint on the root partition. The 4GB limit is not a bad idea at all because you can easily select software in arch-anywhere installer that requires more than 3GB. Do you mind closing the issue?
