### ISSUE TITLE
lspci: blocked for more than 120 secondes

### ISSUE THREAD

**Issue by beauraF** [deadhead420/arch-linux-anywhere#344]
Hi,

I wanted to use arch-anywhere on my new Dell XPS 15, but when I run the installer I have an error : 

```
INFO: task lspci: 534 blocked for more than 120 secondes.
   Not tainted: 4.10.13-1-ARCH #1
echo 0 > /proc/sys/kernel/hung_task_timeout_secs" disables this message.
```

Someone have a fix ?

Thanks.

**Comment by beauraF** [comment]
Ok,
I remove the `lspci` call in `arch-anywhere.conf. After that, I managed to install my arch.

But, lspci and shutdown / reboot hangs.
I followed the indications of this thread to solve the worry : https://bbs.archlinux.org/viewtopic.php?id=183185

I do not know if that's a good solution. An opinion ?

**Comment by deadhead420** [comment]
Very strange. The reason I'm using the lspci command is to detect the graphics chipset, but I've never seen it hang. I would imagine it has to be a hardware related issue but would require some troubleshooting to figure out. Closing issue for now as I believe its related to your hardware. I've installed arch probably on about 100 different computers and my experience is almost every system is different in terms of strange issues that pop up. I have a few different laptops (also macbook) which I've struggled for days to get Arch working right. If you have asolution that works go for it otherwise the only thing you can do is keep digging. Good luck.

**Comment by beauraF** [comment]
I also think it's hardware. At least it makes some documentation.

Thanks for your time @deadhead420.
