### ISSUE TITLE
arch-anywhere installer does not detect IPv6 only connection

### ISSUE THREAD

**Issue by hax404** [deadhead420/arch-linux-anywhere#372]
Hi,
here I have a kvm based hypervisor that only provides a IPv6 connection to the internet. Router advertisements and rdnssd work well. So pings to destinations that are reachable over IPv6 work.
I start the installer with `arch-anywhere`. After the language selection I get this error message:
`Error: No network connection exiting installer.`
The iptest tool says
`Pass: Active internet connection detected`

I used the iso arch-anywhere-2.2.7-2-x86_64.iso . To reproduce this you need a network that has only a RAdv. Here I use bird6 with this small configuration:
```
protocol radv {
    interface "br0";
    prefix 2001:bc8:XXXX::/64 {
    };
    rdnss {
        ns 2001:4860:4860::8888;
        ns 2001:4860:4860::8844;
    };
}
```

I think there is a check in the installer that only tests if IPv4 works.

**Comment by pnedkov** [comment]
1. I assume you are using wired connection but wanted to double check.
2. Does this command work:
`curl https://www.archlinux.org/mirrorlist/all/`
3. How about this one:
`curl -6 https://www.archlinux.org/mirrorlist/all/`

**Comment by hax404** [comment]
> I assume you are using wired connection but wanted to double check.

Yes, it is wired. lcpci says that the kernel driver is virtio-pci and the kernel module virtio_pci

> Does this command work:
> curl https://www.archlinux.org/mirrorlist/all/
> How about this one:
> curl -6 https://www.archlinux.org/mirrorlist/all/

Both work. When I add -v I see that curl connects to 2a01:4f8:172:1d86::1 and do a TLSv1.2 handshake.

**Comment by hax404** [comment]
I did a tcpdump. There i see that something does a DNS lookup for github.com. As I know github does not IPv6. So at first i need to set up nat64 on the hypervisor.

**Comment by pnedkov** [comment]
We do `wget -q --spider github.com` to check the internet connection. And I do not see any AAAA records for github.com. This could be the problem.
`dig github.com any`

As a work-around try this: Open `configure_connection.sh` script and change github.com in the wget command to some domain that has AAAA record - google.com for instance. In fact we have been checking the connection using google.com but some people complained that google.com is being blocked in their country so we changed it to github.com... Which apparently is not the best choice since it does not work for another group of people.

Sorry for the late reply.

**Comment by deadhead420** [comment]
Fixed. I changed the command used to check connection to: ping google.com -W 2 -c 1

This works just as well and will fix the issue if a user is on ipv6 only.

**Comment by Marksion08** [comment]
What to do next ?
> curl https://www.archlinux.org/mirrorlist/all/   ## **OK**
How about this one:
> curl -6 https://www.archlinux.org/mirrorlist/all/   ## **Fail**
