### ISSUE TITLE
can't boot with GTX 970 unless "using" with nomodeset

### ISSUE THREAD

**Issue by ahjolinna** [deadhead420/arch-linux-anywhere#374]
I and other GTX 970 users have notice that Arch based distros (at least) ISOs have problems with booting properly, and this affects also arch-anywhere...it's seems using nomodeset does help.

Arch based distros that have this problem are at least: Manjaro(-kde) 16.xx, [Antergos](https://github.com/Antergos/antergos-iso/issues/68) and [chakraOS](https://gitlab.chakralinux.org/tools/chakra-iso/issues/34) ...I've tested the latest Manjaro 17.0.x ISO and this issue has been resolved (probably because of the rework done on the booting process side)

one of my friends @ansraliant who also has GTX 970 has also confirmed all of this (more or less)

**Comment by ansraliant** [comment]
As @ahjolinna said, I am having the same issue when booting with the 970. Issue does not happen when using integrated graphics.

**Comment by pnedkov** [comment]
Hi,

Thanks for reporting this. The Arch Anywhere ISO file is based on the official Arch Linux iso. The script that generates the Arch Anywhere iso takes the official Arch Linux iso, unpacks it, integrates the Arch Anywhere installer in it (which is nothing more but a bunch of scripts), adds some minor tweaks (vconsole.conf, generate all supported locales etc.) and packages back a new iso with the new content. If you are experiencing a problem with the Arch Linux iso the chances are you will have the same problem with the Arch Anywhere iso. Not much could be done within the scope of Arch Anywhere in order to address that. In other words you should report the issue to upstream. Good luck.

**Comment by deadhead420** [comment]
I also happen to have a gtx 970 and have faced the same issue... The issue is with the Arch ISO not Arch Anywhere. As mentioned above Arch Anywhere is just a repackaged archiso. The solution, as you said is to set "nomodeset" on the kernel command line before boot. The issue has technically been solved.

**Comment by pnedkov** [comment]
@deadhead420 , I need a little help here. I installed an nvidia card in one of my computers and when I boot from arch anywhere or the stock arch linux iso the image is corrupted - completely unreadable. I don't see where I can specify this "nomodeset" option. I get a prompt with 2 options: 1. Booting from Arch and 2. Boot in UEFI shell (do not remember exactly). I don't see the linux boot prompt at all. Any ideas?

**Comment by deadhead420** [comment]
@pnedkov 

When you boot into the bootloader menu screen quickly press "e" on the Arch Linux boot option. This will stop the timeout and allow you to edit the kernel command line before boot. Simply add a space and append "nomodeset". Then press enter to boot with kernel mode setting disabled

**Comment by pnedkov** [comment]
@deadhead420 
Yes, I am aware of that, but for some reason I do not see that bootloader menu. I will try again soon.

**Comment by pnedkov** [comment]
Got the linux bootloader menu at last! These old SuperMicro motherboards are tricky. "nomodeset" worked out great and I have a brand new system!

**Comment by deadhead420** [comment]
Glad to hear!
