### ISSUE TITLE
lightdm.service failed (and solution)

### ISSUE THREAD

**Issue by TripMix** [deadhead420/arch-linux-anywhere#51]
I've noticed the lightdm.service is sometimes not being started what I did to fix was:

systemctl enable lightdm.service
pacman -S lightdm-gtk-greeter
pacman -S xf86-video-nouveau lib32-mesa-libgl

(Recommend users with AMD GPU's try xf86-video-amdgpu and lib32-mesa-libgl, since I have no means of testing this I cannot comment on success rate)

**Comment by deadhead420** [comment]
Enabling lightdm should not be necessary because it is enabled in the installer, also lightdm-gtk-greeter is installed. Which tells me something is off with your drivers. What chipset do you have? And also what version of nvidia drivers did you select latest or legacy? A simple way to display all this info is with:

`lspci -k | grep -A3 VGA`

That command will show you the chipset, kernel driver in use and the loaded modules. The lib32 package is multilib specific so should not be required. Will do some testing on my GTX 970, also have a computer with AMD & intel graphics I can test on. I will keep this issue open for now but plan on closing it if I can not recreate. I've added xf86-video-nouveau to the installer for nvidia users which I think is all that needed to be done to fix the problem. Will let you know what I find out

**Comment by deadhead420** [comment]
Releasing 2.2.3 soon going to close this issue for now. I haven't been able to recreate this issue as of yet. Let me know if it still happens for you in the latest release
