### ISSUE TITLE
Weird font when installing i3

### ISSUE THREAD

**Issue by Kurolox** [deadhead420/arch-linux-anywhere#55]
It seems like installing i3 using the arch-anywhere installer leads to problem with font. Here's a screenshot.

https://cdn.discordapp.com/attachments/207134135431462913/214545336981651456/unknown.png

I can't determine if It's exclusive of i3 or what it's causing it. I'm doing tests right now. The system is being installed in a x64 laptop, but it seems like other people have reported the same problem in a VM, so I doubt that this is an isolated problem.

**Comment by deadhead420** [comment]
Woah! Strange! Have never seen this.... Could be due to xorg font configs not being installed... Not too sure. I haven't tested i3 since I added it which was over a year ago. I'll run an install in vbox to see if I can get to the bottom of it. In the mean time I would recommend checking the wiki and making sure xorg fonts are installed and configured correctly

**Comment by condor2** [comment]
What installation language?

**Comment by Kurolox** [comment]
The installation language was English. I'll do it again to enumerate each step I did in the installation so we can check if it's reproducible. I'll edit this and add it when I finish.

**Comment by elusiveity** [comment]
Just leaving a comment because this came up in my google search.

I installed lightdm (like kurolox) and it fixed my issue. Previously, I attempted setting the fonts to Lyx because that's all I had installed (from what I could tell). 

Once I installed lightdm, I mod+shift+r'ed and it's all fixed, which is why it started working for op. This is a font config related issue.
