### ISSUE TITLE
question: bypassing arch-anywhere-creator.sh

### ISSUE THREAD

**Issue by phenri** [deadhead420/arch-linux-anywhere#62]
Which is the short way to edit arch-installer.sh without creating a new iso?

**Comment by condor2** [comment]
You can edit after boot **/usr/bin/arch-anywhere**. Or from local machine to copy on virtual box machine after boot.

**Comment by deadhead420** [comment]
The executeable for arch-anywhere is located at: /usr/bin/arch-anywhere
The configuration file for arch-anywhere is located at: /etc/arch-anywhere.conf
The language files for arch anywhere are at: /usr/share/arch-anywhere/lang
Other misc files and desktop configuration are all under: /usr/share/arch-anywhere

**Comment by phenri** [comment]
I don't get it, how I can test my changes in that files without rebuild an ISO. How do you to test changes without any build from the beginning? Can you detail the process please? Thank's

**Comment by condor2** [comment]
https://www.howtoforge.com/moving-files-between-linux-systems-with-scp

**Comment by deadhead420** [comment]
I assume you're using virtualbox. You must go into the settings for your virtualbox system. Under network settings you must set to bridged network. Next oot into the ISO. Once booted run the command:

systemctl start sshd

Then run the command:

passwd

set the password to whatever you like, I use something easy like 123 it doesn't really matter.
Next run the command:

4 
OR: 
ip addr

Find the local ip for the virtual system. example: 192.168.1.2
Once you have ssh started, a root password set, and the local IP you can open a terminal on your host system.

Run the command:

ssh root@192.168.1.2
(Note replace the IP address with the correct IP for your virtual system)
This allows you to control the virtual system and test the install from a terminal on your host system rather than being stuck in a vbox window.

To copy files over to the system use scp. From host system:

scp arch-installer.sh root@192.168.1.2:/usr/share/arch-anywhere
(note again use correct IP)

**Comment by phenri** [comment]
Thank you, it works! :)
