### ISSUE TITLE
Installation stuck on checking internet connection

### ISSUE THREAD

**Issue by rgb4u** [deadhead420/arch-linux-anywhere#64]
Hi, i'm on clean, new installation on Windows7, when i try to install arch-anywhere on virtualbox 5,
its check the connection to inthernet, and its stuck on 100%
I tried disconnect inthernet, reboot system, update win7, without results
I can't install this on VB, after few hours of waiting
Also, what can be a case for screen tearing/flickering in any kde based linux distro?
I'm on amd processor and dual radeon graphics(asus)

**Comment by condor2** [comment]
How network was setting on virtualbox?

**Comment by deadhead420** [comment]
This should be fixed now. I changed it so it uses arch mirror to test
connection rather than the test link I was using before.

**Comment by deadhead420** [comment]
Should be fixed in the update but still a strange error. Be sure to check network settings for the virtualbox syste. Going to close this issue, I've made many updates to this part of the script. I was using a test link I found on google to fetch a 1MB file in order to test the users connection speed. My guess is this link was not responsive for you for whatever reason and as a result froze when trying to download it. I've changed the script to use a link from the arch mirrorlist instead so it will test your speed to the mirror not a test link. Closing this issue as it should now be resolved. If you're able to test again with 2.2.3 and you still have this issue please open this issue again.

**Comment by D0048** [comment]
Still experiencing the same.
