### ISSUE TITLE
Installer Not seeing NVMe Drive 

### ISSUE THREAD

**Issue by MBuchaus** [deadhead420/arch-linux-anywhere#85]
First Great work.  this is so needed for Arch.  and I've used your installer on my ASUS and multiple VM's.   I wanted to use the installer on my Lenovo P50 with 
Non-Volatile memory controller: Samsung Electronics Co Ltd NVMe SSD Controller (rev 01)  
blkid shows  /dev/nvme0n1p1-p5  (existing partitions). 
the installer however only had the sda drive available.

**Comment by Dome91** [comment]
I havea Dell XPS 15 and faced a similiar problem.
I had to change the SATA configuration from RAID to AHCI in the BIOS for the NVMe SSD to show up.

**Comment by deadhead420** [comment]
This should be fixed for the next release. I changed the way the script detects drives/partitions. Before it searched for only "sd.." devices, it should search for everything under /dev now granted it shows up in fdisk. Don't have a way to test this because I don't have a NVMe drive but it should be working in the next release (2.2.4). Please re-open issue if the problem continues.

**Comment by 3kynox** [comment]
Hello,

I experienced same problem using latest install package. No NVMe disk showing.
I got an XPS 15 9560. And I don't want to switch to AHCI.

Thanks for help.

**Comment by deadhead420** [comment]
Are you using automatic or manual partitioning?

**Comment by 3kynox** [comment]
Manual. Just tried few things, looks like the RAID mode in bios is in fault, AHCI detected correctly.
However, I would like keep RAID mode.

Currently doing some research about what's exactly supported or not in kernel.
